server:
  port: 8889
spring:
  data:
    mongodb:
      username: alvine
      password: password
      host: localhost
      database: customer
      port: 27017
      authentication-database: admin
