server:
  port: 8899
spring:
  datasource:
    url: jdbc:postgresql//localhost:5433/orders
    username: alvine
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
application:
  config:
    customer-url: http://localhost:8822/api/v1/customers
    product-url: http://localhost:8822/api/v1/products
    payment-url: http://localhost:8822/api/v1/payments