server:
  port: 8899
spring:
  datasource:
    url: jdbc:postgresql//localhost:5433/orders
    username: alvine
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect